### ISSUE TITLE
Investigate PnL calculation

### ISSUE THREAD

**Issue by JChiaramonte7** [Kwenta/kwenta-subgraph#11]
- [x] Add basic PnL summation to subgraph
- [x] Verify PnL includes funding
- [x] Determine if we should have a separate subgraph for the futures competition

**Comment by Tburm** [comment]
PnL does not include funding. We will include a separate value that tracks net funding over time, that way wherever we need to calculate P&L we can do so including fees, funding, and trading gains/losses separately.

**Comment by Tburm** [comment]
In terms of a separate subgraph, I actually think a short-lived competition subgraph is our best option. If we use the current subgraph, we will need to aggregate the data from every position within a set of timestamps.

With a separate subgraph, we could simply set the start block and sum all P&L across the period for each address.
